//go:build ignore
// +build ignore

// This file is intended to be executed via `go generate`.
// It produces a `version_gen.go` file, which contains build-time metadata.

package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

func main() {
	buildDate := time.Now().UTC().Format(time.RFC3339)
	gitCommit := "unknown"

	if out, err := exec.Command("git", "rev-parse", "--short", "HEAD").Output(); err == nil {
		gitCommit = strings.TrimSpace(string(out))
	}

	f, err := os.Create("version_gen.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to create version_gen.go: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprint(f, `// Code generated by go generate; DO NOT EDIT.

package version

// BuildDate is the UTC date/time when the binary was built.
var BuildDate = "`+buildDate+`"

// GitCommit is the short SHA1 of the git commit used to build the binary.
var GitCommit = "`+gitCommit+`"
`)
}
