// Code generated by go generate; DO NOT EDIT.

package version

// BuildDate is the UTC date/time when the binary was built.
var BuildDate = "2026-03-15T08:33:53Z"

// GitCommit is the short SHA1 of the git commit used to build the binary.
var GitCommit = "894baf5"
